### ISSUE TITLE
Any class name for Mythos?

### ISSUE THREAD

**Issue by Pokotuz** [Karageek/AtlasHarvestResourceList#1]
It is rare item but sometimes player need a shortcut :P 
So, Is there a class name for this one?

**Comment by Karageek** [comment]
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemResource_MagicMarrow_C",Multiplier=1.000000)   This is Mythos

Cheat gfi MagicMarrow 1 0 0  will give you 1 mythos  edit 1 up to 2000 per stack.
