### ISSUE TITLE
Technicality

### ISSUE THREAD

**Issue by smooreace** [Karageek/AtlasHarvestResourceList#2]
This is actually the proper way to modify harvest rates. Using the harvestratemultiplier is very hard on server performance. And it gets exponentially harder as rate increase! 

Tests in Ark harvesting 100 brontos at 10x with harvestratemultiplier let to a 10 to 15 second server seizure with some people being disconnected
.
Testing with all the way up to 500 brontos using this method at 100x multiplier let to absolutely no server hit at all.

So everyone SHOULD be using this method exclusively! Then use harvestratemultiplier  for a quick even change in rates

**Comment by Karageek** [comment]
Thank you.
